Feature/assignment 3
Sneha1251/React-Training pull request #3
Opened 2024-04-04 18:30 UTC by Sneha1251

2024-04-12 10:48 UTC, DevGarima requested changes

2024-04-12 10:48 UTC, DevGarima commented on react-app/src/Assignment-3/Question6/Products.jsx
> +const items = [
create new file constants.js
export const items = [

2024-04-12 10:48 UTC, DevGarima commented on react-app/src/Assignment-3/Question2/Question-2.jsx
> +const PreferencesProvider = () => {
Use another file for creating context from next time onwards.

2024-04-12 10:48 UTC, DevGarima commented on react-app/src/Assignment-3/Question6/Products.jsx
> +export { items };
remove the items from here

2024-04-12 10:48 UTC, DevGarima commented on react-app/src/Assignment-3/Question4/Login.jsx
> +            setname(e.target.value);
follow camelCase for all name, event handler

2024-04-12 10:48 UTC, DevGarima commented on react-app/src/Assignment-3/Question4/Protected.jsx
> +    let login = localStorage.getItem("login");
use const

2024-04-12 10:48 UTC, DevGarima commented on react-app/src/Assignment-3/Question4/Question-4.jsx
> + return(
make one file for all routes as currently created for each module seperatly.

2024-04-12 10:48 UTC, DevGarima commented on react-app/src/Assignment-3/Question3/Question-3.jsx
> +
add component for 404 page

2024-04-12 10:48 UTC, DevGarima commented on react-app/src/Assignment-3/Question4/Protected.jsx
> +const Protected = (props) => {
use proper name in all places

2024-04-15 07:21 UTC, Sneha1251 commented on react-app/src/Assignment-3/Question2/Question-2.jsx
> +const PreferencesProvider = () => {
Done

2024-04-15 07:22 UTC, Sneha1251 commented on react-app/src/Assignment-3/Question3/Question-3.jsx
> +
Done

2024-04-15 07:23 UTC, Sneha1251 commented on react-app/src/Assignment-3/Question4/Login.jsx
> +            setname(e.target.value);
done

2024-04-15 07:27 UTC, Sneha1251 commented on react-app/src/Assignment-3/Question6/Products.jsx
> +const items = [
Done

2024-04-15 10:17 UTC, DevGarima approved these changes

2024-04-15 10:17 UTC, merged